apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-processor
  labels:
    app: sqs-processor
spec:
  replicas: 1  # Initial replica count, KEDA will scale this
  selector:
    matchLabels:
      app: sqs-processor
  template:
    metadata:
      labels:
        app: sqs-processor
    spec:
      serviceAccountName: sqs-processor-sa
      containers:
      - name: sqs-processor
        image: public.ecr.aws/f8u4w2p3/rust-sqs-processor:1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: sqs-processor-config
        # AWS credentials are provided via IAM roles for service accounts (IRSA)
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
