apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sqs-processor-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: sqs-processor  # Name of the deployment to scale
  minReplicaCount: 0     # Minimum number of replicas
  maxReplicaCount: 10    # Maximum number of replicas
  pollingInterval: 15    # How frequently to check the metrics (in seconds)
  cooldownPeriod: 300    # Period to wait after last trigger before scaling down
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: TODO  # Replace with your SQS queue URL
      queueLength: "5"   # Target messages per pod
      awsRegion: "us-west-2"  # Replace with your AWS region
      identityOwner: "operator"  # Use IAM role attached to KEDA operator's service account
